import React from "react";
import Nav from "../components/User/Nav";
import Head from "next/head";
import Layout from "../components/Admin/Layout";
import styles from "../styles/Home.module.css";
const adminNav = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Admin Layout</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <Layout />
      {/* <Nav /> */}
    </>
  );
};

export default adminNav;
