import React from 'react'
import Layout from "../components/Admin/Layout"
import Head from 'next/head'
const userLayout = () => {
  return (
    
    <div>
        <Head>
        <title>UserLayout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout/>
      </div>
  )
}

export default userLayout